blueprint:
  name: "Gestione Completa Panda (Giorgio)"
  description: >
    Unifica il monitoraggio consegne, la gestione automatica del GPS (Alta Precisione)
    e gli avvisi di rientro in sede.
  domain: automation
  input:
    # --- Dispositivi ---
    panda_tracker:
      name: Tracker Panda
      description: "Il device tracker della Panda (es. device_tracker.panda)"
      selector:
        entity:
          domain: device_tracker
    mobile_app_notify:
      name: Notifica App Mobile (GPS)
      description: "Servizio notifica app per attivare il GPS (es. notify.mobile_app_panda)"
      selector:
        text:
    
    # --- Zone ---
    base_zone:
      name: Zona Pizzeria (Base)
      description: "La zona di partenza (es. zone.pizzeria)"
      selector:
        entity:
          domain: zone

    # --- Notifiche ---
    alexa_targets:
      name: Dispositivi Alexa
      description: "Dispositivi per gli annunci vocali."
      default: 
        - notify.echo_show_di_giorgia_annuncio
        - notify.echo_show_di_giorgia_parla
      selector:
        entity:
          domain: notify
          multiple: true
    telegram_chat_id:
      name: Telegram Chat ID
      description: "Inserisci il tuo Chat ID per i report."
      default: ""
      selector:
        text:

    # --- Helpers (Entità di supporto) ---
    helper_departure_time:
      name: Input Orario Partenza
      selector:
        entity:
          domain: input_datetime
    helper_arrival_time:
      name: Input Orario Arrivo
      selector:
        entity:
          domain: input_datetime
    helper_travel_minutes:
      name: Input Minuti Viaggio
      selector:
        entity:
          domain: input_number
    helper_in_delivery:
      name: Input Boolean In Consegna
      selector:
        entity:
          domain: input_boolean
    counter_daily:
      name: Contatore Giornaliero
      selector:
        entity:
          domain: counter
    counter_weekly:
      name: Contatore Settimanale
      selector:
        entity:
          domain: counter
    counter_partial:
      name: Contatore Parziale (Annunci)
      selector:
        entity:
          domain: counter

    # --- Orari ---
    time_start_shift:
      name: Inizio Turno
      default: "18:00:00"
      selector:
        time:
